# Dense Retrieval Configuration
# ============================

# Basic experiment info
experiment_id: dense_specter_sentence
task_type: retrieval
description: "Dense retrieval using SPECTER embeddings with sentence-level granularity"

# Data sources
data:
  corpus_path: "rabuahmad/climatecheck_publications_corpus"
  claims_path: "rabuahmad/climatecheck"

# Retriever configuration
retriever:
  type: dense
  model_name: "sentence-transformers/allenai-specter"
  granularity: "sentence"  # Options: document, passage, sentence
  params:
    k: 10  # Number of documents to retrieve
    content_type: "abstract_only"

# Evaluation settings
evaluation:
  k_values: [2, 5, 10]  # K values for recall@k and precision@k calculations